<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>前程贷接口自动化测试</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">前程贷接口自动化测试</h1>
<p class='attribute'><strong>测试人员 : </strong> davis</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-10-24 17:19:30</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:31.857000</p>
<p class='attribute'><strong>测试结果 : </strong> 共 51，失败 51，通过率= 0.00%</p>

<p class='description'>金融项目类P2P接口自动化测试</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 51 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 51 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>test_02_login.TestLogin</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',6)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='failCase'><div class='testcase'>test_login_1_正确的手机号和密码登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":1,"code":"10001","data":null,"msg":"登录成功"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?           ^        ^^^^                    -----  ^
+ {"status":1,"code":"10001","data":null,"msg":"登录成功"}
?           ^        ^^^^^^^                      ^^
 : 测试正确的手机号和密码登录


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='failCase'><div class='testcase'>test_login_2_错误的手机号和密码</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?                    ^^^^                    ^^^^^^^^
+ {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
?                    ^^^^^^^                    ^^^^^^^^
 : 测试错误的手机号和密码


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='failCase'><div class='testcase'>test_login_3_手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?                    ^^^^                    ^^^^^^^^
+ {"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}
?                    ^^^^^^^                    ^^^^^^^
 : 测试手机号为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_login_4_密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?                    ^^^^                    ^^^^^^^^
+ {"status":0,"code":"20103","data":null,"msg":"密码不能为空"}
?                    ^^^^^^^                    ^^^^^^
 : 测试密码为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='failCase'><div class='testcase'>test_login_5_正确的手机号和错误的密码</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?                    ^^^^                    ^^^^^^^^
+ {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
?                    ^^^^^^^                    ^^^^^^^^
 : 测试正确的手机号和错误的密码


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_login_6_错误的手机号和正确的密码</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_02_login.py", line 63, in test_login
    raise e
  File "D:\code\api_test\datas\test_02_login.py", line 55, in test_login
    self.assertEqual(ret.text, expected, msg)
AssertionError: '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
- {"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}
?                    ^^^^                    ^^^^^^^^
+ {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
?                    ^^^^^^^                    ^^^^^^^^
 : 测试错误的手机号和正确的密码


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_03_recharge.TestRecharge</td>
    <td class="text-center">12</td>
    <td class="text-center">0</td>
    <td class="text-center">12</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',12)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_01_投资人登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>失败</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人登录


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_02_充值成功_整数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>失败</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值成功-整数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_03_充值成功_1位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值成功-1位小数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_04_充值成功_2位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值成功-2位小数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_05_充值成功_50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>失败</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>失败</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值成功-50万


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_06_手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20103' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试手机号为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_07_充值金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse in" align="left">
    <pre>
    
ft2_7: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20115' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值金额为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_8' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_08_手机号不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse in" align="left">
    <pre>
    
ft2_8: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20104' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试手机号不存在


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_9' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_09_手机号小于11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse in" align="left">
    <pre>
    
ft2_9: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20109' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试手机号小于11位


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_10' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_10_充值金额3位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse in" align="left">
    <pre>
    
ft2_10: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20116' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值金额3位小数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_11' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_11_充值金额大于50万</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse in" align="left">
    <pre>
    
ft2_11: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20117' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值金额大于50万


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_12' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_12_充值金额非数字</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse in" align="left">
    <pre>
    
ft2_12: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_03_recharge.py", line 84, in test_recharge
    raise e
  File "D:\code\api_test\datas\test_03_recharge.py", line 64, in test_recharge
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20118' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试充值金额非数字


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_04_add.TestAdd</td>
    <td class="text-center">17</td>
    <td class="text-center">0</td>
    <td class="text-center">17</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',17)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='failCase'><div class='testcase'>test_add_01_借款人登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款人登录


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='failCase'><div class='testcase'>test_add_02_正确加标</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试正确加标


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='failCase'><div class='testcase'>test_add_03_借款人id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20103' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款人id为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='failCase'><div class='testcase'>test_add_04_借款人id不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20105' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款人id不存在


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='failCase'><div class='testcase'>test_add_05_借款人id非正整数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20104' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款人id非正整数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='failCase'><div class='testcase'>test_add_06_借款金额小于1000</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20106' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额小于1000


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='failCase'><div class='testcase'>test_add_07_借款金额为2位小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20106' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额为2位小数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_8' class='none'>
    <td class='failCase'><div class='testcase'>test_add_08_借款金额为负数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse in" align="left">
    <pre>
    
ft3_8: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20106' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额为负数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_9' class='none'>
    <td class='failCase'><div class='testcase'>test_add_09_借款金额不能被100整除</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse in" align="left">
    <pre>
    
ft3_9: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20106' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额不能被100整除


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_10' class='none'>
    <td class='failCase'><div class='testcase'>test_add_10_借款金额为非正整数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse in" align="left">
    <pre>
    
ft3_10: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20106' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额为非正整数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_11' class='none'>
    <td class='failCase'><div class='testcase'>test_add_11_借款金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse in" align="left">
    <pre>
    
ft3_11: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20103' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款金额为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_12' class='none'>
    <td class='failCase'><div class='testcase'>test_add_12_借款利率小于0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse in" align="left">
    <pre>
    
ft3_12: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20107' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款利率小于0


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_13' class='none'>
    <td class='failCase'><div class='testcase'>test_add_13_借款利率等于0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse in" align="left">
    <pre>
    
ft3_13: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20107' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款利率等于0


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_14' class='none'>
    <td class='failCase'><div class='testcase'>test_add_14_借款利率大于24</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_14'>失败</button>
    <div id='div_ft3_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_14'>失败</button>
    <div id='div_ft3_14' class="collapse in" align="left">
    <pre>
    
ft3_14: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20107' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款利率大于24


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_15' class='none'>
    <td class='failCase'><div class='testcase'>test_add_15_借款日期类型不等于0_2_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_15'>失败</button>
    <div id='div_ft3_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_15'>失败</button>
    <div id='div_ft3_15' class="collapse in" align="left">
    <pre>
    
ft3_15: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20108' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款日期类型不等于0,2,4


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_16' class='none'>
    <td class='failCase'><div class='testcase'>test_add_16_借款日期类型为小数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_16'>失败</button>
    <div id='div_ft3_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_16'>失败</button>
    <div id='div_ft3_16' class="collapse in" align="left">
    <pre>
    
ft3_16: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20109' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款日期类型为小数


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_17' class='none'>
    <td class='failCase'><div class='testcase'>test_add_17_借款日期类型为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_17'>失败</button>
    <div id='div_ft3_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_17'>失败</button>
    <div id='div_ft3_17' class="collapse in" align="left">
    <pre>
    
ft3_17: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_04_add.py", line 66, in test_add
    raise e
  File "D:\code\api_test\datas\test_04_add.py", line 57, in test_add
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '20103' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试借款日期类型为空


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_05_invest.TestInvest</td>
    <td class="text-center">16</td>
    <td class="text-center">0</td>
    <td class="text-center">16</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',16)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_01_管理员正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试管理员正常登录


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_02_管理员加标</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse in" align="left">
    <pre>
    
ft4_2: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试管理员加标


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_03_管理员审核</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试管理员审核


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_4' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_04_投资人正常登录</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse in" align="left">
    <pre>
    
ft4_4: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人正常登录


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_5' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_05_投资人正常投资</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_5'>失败</button>
    <div id='div_ft4_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_5'>失败</button>
    <div id='div_ft4_5' class="collapse in" align="left">
    <pre>
    
ft4_5: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '10001' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人正常投资


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_6' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_06_投资人id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_6'>失败</button>
    <div id='div_ft4_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_6'>失败</button>
    <div id='div_ft4_6' class="collapse in" align="left">
    <pre>
    
ft4_6: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11003' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人id为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_7' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_07_投资人密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_7'>失败</button>
    <div id='div_ft4_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_7'>失败</button>
    <div id='div_ft4_7' class="collapse in" align="left">
    <pre>
    
ft4_7: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11003' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人密码为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_8' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_08_标id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse in" align="left">
    <pre>
    
ft4_8: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11003' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试标id为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_9' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_09_投资金额为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_9'>失败</button>
    <div id='div_ft4_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_9'>失败</button>
    <div id='div_ft4_9' class="collapse in" align="left">
    <pre>
    
ft4_9: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11003' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资金额为空


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_10' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_10_投资人id为0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_10'>失败</button>
    <div id='div_ft4_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_10'>失败</button>
    <div id='div_ft4_10' class="collapse in" align="left">
    <pre>
    
ft4_10: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11004' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人id为0


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_11' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_11_标id为0</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_11'>失败</button>
    <div id='div_ft4_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_11'>失败</button>
    <div id='div_ft4_11' class="collapse in" align="left">
    <pre>
    
ft4_11: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11009' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试标id为0


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_12' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_12_投资人密码小于6位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_12'>失败</button>
    <div id='div_ft4_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_12'>失败</button>
    <div id='div_ft4_12' class="collapse in" align="left">
    <pre>
    
ft4_12: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11006' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人密码小于6位


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_13' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_13_投资人密码大于18位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse in" align="left">
    <pre>
    
ft4_13: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11006' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人密码大于18位


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_14' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_14_投资金额不能被100整除</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_14'>失败</button>
    <div id='div_ft4_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_14'>失败</button>
    <div id='div_ft4_14' class="collapse in" align="left">
    <pre>
    
ft4_14: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11007' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资金额不能被100整除


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_15' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_15_投资人id不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_15'>失败</button>
    <div id='div_ft4_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_15'>失败</button>
    <div id='div_ft4_15' class="collapse in" align="left">
    <pre>
    
ft4_15: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11008' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试投资人id不存在


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_16' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_16_标id不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_16'>失败</button>
    <div id='div_ft4_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_16'>失败</button>
    <div id='div_ft4_16' class="collapse in" align="left">
    <pre>
    
ft4_16: Traceback (most recent call last):
  File "D:\code\api_test\libs\ddt.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "D:\code\api_test\datas\test_05_invest.py", line 73, in test_invest
    raise e
  File "D:\code\api_test\datas\test_05_invest.py", line 64, in test_invest
    self.assertIn(str(expected), ret.text, msg)
AssertionError: '11009' not found in '{"status":0,"code":null,"data":null,"msg":"抱歉，请先登录。"}' : 测试标id不存在


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>51</td>
    <td>0</td>
    <td>51</td>
    <td>0</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
